In [1]:
# !pip install nbconvert==6.0.0
!pip install flask

Defaulting to user installation because normal site-packages is not writeable
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.


In [2]:
#pip install gensim
!pip install transformers

Defaulting to user installation because normal site-packages is not writeable
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.


In [3]:
# !pip install urduhack

In [4]:
# import spacy
# !pip install sklearn
# !pip install pandas


## Processing Dataset (Urdu-Poetry)

In [1]:

from spacy import blank

# import urduhack 
from urduhack.normalization import normalize
from urduhack.preprocessing import normalize_whitespace 
from urduhack.preprocessing import remove_accents

# import pandas
import pandas as pd

# import sklearn
from sklearn import svm  
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import classification_report, confusion_matrix
import csv
import pandas as pd
import numpy as np
# read dataset from file

filename = "/home/manzur/Documents/Urdu/Urdu_corp_source.csv"
urdu_source = pd.read_csv(filename, encoding="utf8", usecols=['Data','Label'])
urdu_source = urdu_source.dropna() #removing 'NaN' values from data
data = urdu_source['Data']

labels = pd.unique(urdu_source['Label']).tolist()

urdu_dict = {}

for label in labels:
    label_data = pd.unique(urdu_source[urdu_source['Label'] == label]['Data'])
    # convert labeled data to string
    string_data = ' '.join([str(elem) for elem in label_data])

    #normalization
    urdu_source['Data'] = urdu_source['Data'].apply(normalize)
    urdu_source['Data'] = urdu_source['Data'].apply(remove_accents)
    urdu_source['Data'] = urdu_source['Data'].apply(normalize_whitespace)
   

    # create blank document
    word_blank_page = blank('ur')

    # place dataset into document
    doc = word_blank_page(string_data)

    text = doc.text

     #clean text
    text = text.replace('[', '')
    text = text.replace(']', '')
    text = text.replace("'", '')

    # convert to list of words
    words = text.split(' ')
    print("{} words: {}".format(label, len(words)))
    
    #urdu_dict[label] = words

Sad words: 18229
Patriotic words: 6337
Comic words: 6377
Religious words: 5667


In [2]:
with open("/home/manzur/Downloads/stopwords-ur.txt", 'r', encoding='utf8') as f:
    STOP_WORDS = f.read().replace("\n", " ")
def remove_stopwords(text: str):
   return " ".join(word for word in text.split() if word not in STOP_WORDS)
urdu_source['Data'] = urdu_source['Data'].apply(remove_stopwords)
urdu_source['Data']

0       نہ سنگ خشت درد سے بھر نہ روئیں ہم ہزار بار ہمی...
1       بازیچۂ اطفال دنیا مرے آگے ہوتا شب روز تماشا مر...
2       نہ ہماری قسمت وصال یار ہوتا جیتے رہتے یہی انتظ...
3       بات تم کیا تمہیں انداز گفتگو کیا نہ شعلہ میں ک...
4       ہزاروں خواہشیں ایسی خواہش دم نکلے بہت نکلے مرے...
                              ...                        
4320    نبیﷺ جانے سر اپنے وہاں جھکانے بیٹھ سبز گنبد چھ...
4321    جو سہارا بےکسوں کا ، سنبھال گا پالا جس نے اب أ...
4322    مل عاشقوں خوشیاں منائیں آؤ سرکارﷺ آمد ہم بھی ج...
4323    مصطفیﷺ محبت جو میں بسائے گا زندگی غم سارے رب ا...
4324    میری عبادات دوزخ ڈر سے دوزخ میں مجھ جلا دینا ی...
Name: Data, Length: 297, dtype: object

In [3]:
#Splitting dataset into training and testing parts.
X_train, X_test, Y_train, Y_test = train_test_split(urdu_source['Data'], urdu_source['Label'],test_size = 0.20, random_state = 7, shuffle = True)
#applying 
max_feature_num = 5000
vectorizer = TfidfVectorizer(max_features=max_feature_num)
train_vecs = vectorizer.fit_transform(X_train)
test_vecs = TfidfVectorizer(max_features=max_feature_num, vocabulary=vectorizer.vocabulary_).fit_transform(X_test)

#plotting in dataframe
pd.DataFrame(test_vecs.toarray(), columns=vectorizer.get_feature_names())

_نظر  relegious        آؤ  آئنہ  آئینہ     آئینے  آئیگی  آئیں        آب  \
0    0.0        0.0  0.000000   0.0    0.0  0.000000    0.0   0.0  0.000000   
1    0.0        0.0  0.000000   0.0    0.0  0.000000    0.0   0.0  0.000000   
2    0.0        0.0  0.000000   0.0    0.0  0.000000    0.0   0.0  0.000000   
3    0.0        0.0  0.000000   0.0    0.0  0.000000    0.0   0.0  0.000000   
4    0.0        0.0  0.000000   0.0    0.0  0.000000    0.0   0.0  0.000000   
5    0.0        0.0  0.000000   0.0    0.0  0.000000    0.0   0.0  0.000000   
6    0.0        0.0  0.000000   0.0    0.0  0.000000    0.0   0.0  0.000000   
7    0.0        0.0  0.000000   0.0    0.0  0.000000    0.0   0.0  0.000000   
8    0.0        0.0  0.000000   0.0    0.0  0.000000    0.0   0.0  0.000000   
9    0.0        0.0  0.000000   0.0    0.0  0.000000    0.0   0.0  0.000000   
10   0.0        0.0  0.000000   0.0    0.0  0.000000    0.0   0.0  0.000000   
11   0.0        0.0  0.000000   0.0    0.0  0.000000    0.0   0.0  0.000000   
12   0.0        0.0  0.000000   0.0    0.0  0.000000    0.0   0.0  0.000000   
13   0.0        0.0  0.000000   0.0    0.0  0.000000    0.0   0.0  0.000000   
14   0.0        0.0  0.000000   0.0    0.0  0.000000    0.0   0.0  0.000000   
15   0.0        0.0  0.000000   0.0    0.0  0.000000    0.0   0.0  0.000000   
16   0.0        0.0  0.000000   0.0    0.0  0.000000    0.0   0.0  0.000000   
17   0.0        0.0  0.000000   0.0    0.0  0.000000    0.0   0.0  0.000000   
18   0.0        0.0  0.000000   0.0    0.0  0.000000    0.0   0.0  0.000000   
19   0.0        0.0  0.000000   0.0    0.0  0.000000    0.0   0.0  0.000000   
20   0.0        0.0  0.000000   0.0    0.0  0.000000    0.0   0.0  0.000000   
21   0.0        0.0  0.000000   0.0    0.0  0.000000    0.0   0.0  0.000000   
22   0.0        0.0  0.000000   0.0    0.0  0.000000    0.0   0.0  0.000000   
23   0.0        0.0  0.000000   0.0    0.0  0.000000    0.0   0.0  0.000000   
24   0.0        0.0  0.000000   0.0    0.0  0.000000    0.0   0.0  0.000000   
25   0.0        0.0  0.000000   0.0    0.0  0.089919    0.0   0.0  0.000000   
26   0.0        0.0  0.000000   0.0    0.0  0.000000    0.0   0.0  0.000000   
27   0.0        0.0  0.073975   0.0    0.0  0.000000    0.0   0.0  0.000000   
28   0.0        0.0  0.000000   0.0    0.0  0.000000    0.0   0.0  0.000000   
29   0.0        0.0  0.000000   0.0    0.0  0.000000    0.0   0.0  0.000000   
30   0.0        0.0  0.000000   0.0    0.0  0.000000    0.0   0.0  0.000000   
31   0.0        0.0  0.000000   0.0    0.0  0.000000    0.0   0.0  0.000000   
32   0.0        0.0  0.000000   0.0    0.0  0.000000    0.0   0.0  0.000000   
33   0.0        0.0  0.000000   0.0    0.0  0.000000    0.0   0.0  0.000000   
34   0.0        0.0  0.000000   0.0    0.0  0.000000    0.0   0.0  0.187505   
35   0.0        0.0  0.000000   0.0    0.0  0.000000    0.0   0.0  0.000000   
36   0.0        0.0  0.000000   0.0    0.0  0.000000    0.0   0.0  0.000000   
37   0.0        0.0  0.000000   0.0    0.0  0.000000    0.0   0.0  0.000000   
38   0.0        0.0  0.000000   0.0    0.0  0.000000    0.0   0.0  0.000000   
39   0.0        0.0  0.000000   0.0    0.0  0.000000    0.0   0.0  0.000000   
40   0.0        0.0  0.000000   0.0    0.0  0.000000    0.0   0.0  0.000000   
41   0.0        0.0  0.000000   0.0    0.0  0.000000    0.0   0.0  0.000000   
42   0.0        0.0  0.000000   0.0    0.0  0.000000    0.0   0.0  0.063593   
43   0.0        0.0  0.000000   0.0    0.0  0.000000    0.0   0.0  0.000000   
44   0.0        0.0  0.000000   0.0    0.0  0.000000    0.0   0.0  0.000000   
45   0.0        0.0  0.000000   0.0    0.0  0.000000    0.0   0.0  0.000000   
46   0.0        0.0  0.000000   0.0    0.0  0.000000    0.0   0.0  0.000000   
47   0.0        0.0  0.000000   0.0    0.0  0.000000    0.0   0.0  0.000000   
48   0.0        0.0  0.000000   0.0    0.0  0.000000    0.0   0.0  0.000000   
49   0.0        0.0  0.000000   0.0    0.0  0.000000  

In [5]:
import joblib
from joblib import dump
from sklearn.pipeline import Pipeline
def SVM_classifier(train_vecs, Y_train, test_vecs, Y_test):
    # Training
    SVM = svm.LinearSVC(max_iter=100)
    SVM = SVM.fit(train_vecs, Y_train)

    # Testing
    test_predictionSVM = SVM.predict(test_vecs)
    #pipeline of tfidf and best classifier SVM
    pipeline = Pipeline(steps= [('tfidf',vectorizer),
                            ('model', svm.LinearSVC(max_iter=100))])

# fit the pipeline model with the training data                            
    pipeline.fit(X_train, Y_train)
    dump(pipeline,filename="pipelined.joblib")
    
    return classification_report(test_predictionSVM, Y_test), confusion_matrix(test_predictionSVM, Y_test)

class_report , conf_matrix = SVM_classifier(train_vecs, Y_train, test_vecs, Y_test)
print('Results of SVM CLASSIFIER on TF-IDF Vectorizer\n')
print(class_report)
print(conf_matrix)


Results of SVM CLASSIFIER on TF-IDF Vectorizer

              precision    recall  f1-score   support

       Comic       0.64      0.82      0.72        11
   Patriotic       1.00      0.93      0.97        15
   Religious       0.74      0.88      0.80        16
         Sad       1.00      0.72      0.84        18

    accuracy                           0.83        60
   macro avg       0.84      0.84      0.83        60
weighted avg       0.86      0.83      0.84        60

[[ 9  0  2  0]
 [ 0 14  1  0]
 [ 2  0 14  0]
 [ 3  0  2 13]]


# Random Forest Classifier

In [6]:
from sklearn.ensemble import RandomForestClassifier

def RandomForest_classifier(train_vecs, Y_train, test_vecs, Y_test):
    # Training
    RF = RandomForestClassifier(max_depth=5, n_estimators=10)
    RF.fit(train_vecs, Y_train)

    # Testing
    test_predictionRF = RF.predict(test_vecs)
    return classification_report(test_predictionRF, Y_test), confusion_matrix(test_predictionRF, Y_test)

class_report , conf_matrix = RandomForest_classifier(train_vecs, Y_train, test_vecs, Y_test)
print('Results of RandomForest CLASSIFIER on TF-IDF Vectorizer\n')
print(class_report)

Results of RandomForest CLASSIFIER on TF-IDF Vectorizer

              precision    recall  f1-score   support

       Comic       0.29      0.50      0.36         8
   Patriotic       0.43      0.67      0.52         9
   Religious       0.58      0.61      0.59        18
         Sad       1.00      0.52      0.68        25

    accuracy                           0.57        60
   macro avg       0.57      0.57      0.54        60
weighted avg       0.69      0.57      0.59        60



# Naive Bayes Classifier

In [7]:
from sklearn.naive_bayes import GaussianNB
def NaiveBayes_classifier(train_vecs, Y_train, test_vecs, Y_test):
    # Training
    NB = GaussianNB()
    NB.fit(train_vecs.toarray(), Y_train)

    # Testing
    test_predictionNB = NB.predict(test_vecs.toarray())
    return classification_report(test_predictionNB, Y_test), confusion_matrix(test_predictionNB, Y_test)

class_report , conf_matrix = NaiveBayes_classifier(train_vecs, Y_train, test_vecs, Y_test)
print('Results of NaiveBayes CLASSIFIER on TF-IDF Vectorizer\n')
print(class_report)

Results of NaiveBayes CLASSIFIER on TF-IDF Vectorizer

              precision    recall  f1-score   support

       Comic       0.71      0.77      0.74        13
   Patriotic       0.86      0.86      0.86        14
   Religious       0.53      0.83      0.65        12
         Sad       0.92      0.57      0.71        21

    accuracy                           0.73        60
   macro avg       0.76      0.76      0.74        60
weighted avg       0.78      0.73      0.74        60



# Desicion Tree Classifier

In [8]:
from sklearn.tree import DecisionTreeClassifier
import joblib
from joblib import dump
from sklearn.metrics import accuracy_score
from sklearn.pipeline import Pipeline
def DecisionTree_classifier(train_vecs, Y_train, test_vecs, Y_test):
    # Training
    clf = DecisionTreeClassifier(max_depth=10)
    clf = clf.fit(train_vecs, Y_train)

    # Testing
    test_prediction = clf.predict(test_vecs)
 
    

    return classification_report(test_prediction, Y_test), confusion_matrix(test_prediction, Y_test)

class_report , conf_matrix = DecisionTree_classifier(train_vecs, Y_train, test_vecs, Y_test)
print('Results of DecisionTree CLASSIFIER on TF-IDF Vectorizer\n')
print(class_report)

Results of DecisionTree CLASSIFIER on TF-IDF Vectorizer

              precision    recall  f1-score   support

       Comic       0.57      0.53      0.55        15
   Patriotic       0.79      1.00      0.88        11
   Religious       0.79      0.58      0.67        26
         Sad       0.54      0.88      0.67         8

    accuracy                           0.68        60
   macro avg       0.67      0.75      0.69        60
weighted avg       0.70      0.68      0.68        60



# Logistic Regression Classifier

In [9]:
from sklearn.multiclass import OneVsRestClassifier
from sklearn.linear_model import LogisticRegression
def LogisticRegression_classifier(train_vecs, Y_train, test_vecs, Y_test):
    # Training
    clf = OneVsRestClassifier(LogisticRegression())
    clf.fit(train_vecs.toarray(), Y_train)

    # Testing
    test_prediction = clf.predict(test_vecs.toarray())
    return classification_report(test_prediction, Y_test), confusion_matrix(test_prediction, Y_test)

class_report , conf_matrix = LogisticRegression_classifier(train_vecs, Y_train, test_vecs, Y_test)
print('Results of LogisticRegression CLASSIFIER on TF-IDF Vectorizer\n')
print(class_report)

Results of LogisticRegression CLASSIFIER on TF-IDF Vectorizer

              precision    recall  f1-score   support

       Comic       0.36      1.00      0.53         5
   Patriotic       0.86      1.00      0.92        12
   Religious       0.74      0.74      0.74        19
         Sad       1.00      0.54      0.70        24

    accuracy                           0.73        60
   macro avg       0.74      0.82      0.72        60
weighted avg       0.83      0.73      0.74        60



In [10]:
import urduhack

In [11]:
help (urduhack)

Help on package urduhack:

NAME
    urduhack - Project Entry point

PACKAGE CONTENTS
    about
    command (package)
    config
    conll (package)
    core (package)
    datasets (package)
    models (package)
    normalization (package)
    pipeline (package)
    preprocessing (package)
    stop_words
    tests (package)
    tokenization (package)
    urdu_characters
    utils (package)

CLASSES
    builtins.object
        urduhack.conll.reader.CoNLL
        urduhack.pipeline.core.Pipeline
    
    class CoNLL(builtins.object)
     |  A Conll class to easily load conll-u formats. This module can also load resources by iterating over string.
     |  This module is the main entrance to conll's functionalities.
     |  
     |  Static methods defined here:
     |  
     |  get_fields() -> List[str]
     |      Get the list of conll fields
     |      
     |      Returns:
     |          List[str]: Return list of conll fields
     |  
     |  iter_file(file_name: str) -> Iterator[Tuple]

In [12]:
help (urduhack.urdu_characters
     )

Help on module urduhack.urdu_characters in urduhack:

NAME
    urduhack.urdu_characters

DESCRIPTION
    Complete collection of Urdu Unicode characters.
    Maintainer: Ikram Ali(mrikram1989@gmail.com)
    version = 2020.04.07
    Source = https://github.com/urduhack/urdu-characters

DATA
    FrozenSet = typing.FrozenSet
    URDU_ALL_CHARACTERS = frozenset({'\u0600', '\u0601', '\u0602', '\u0603...
    URDU_ALL_CHARACTERS_UNICODE = {'\u0600': '\u0600', '\u0601': '\u0601',...
    URDU_ALPHABETS = frozenset({'ء', 'آ', 'أ', 'ؤ', 'ئ', 'ا', ...})
    URDU_DIACRITICS = frozenset({'ً', 'ٍ', 'َ', 'ُ', 'ِ', 'ٰ'})
    URDU_DIGITS = frozenset({'۰', '۱', '۲', '۳', '۴', '۵', ...})
    URDU_EXTRA_CHARACTERS = frozenset({'\u0600', '\u0601', '\u0602', '\u06...
    URDU_PUNCTUATIONS = frozenset({'،', '؛', '؟', '٪', '٫', '۔'})
    __annotations__ = {'URDU_ALL_CHARACTERS': typing.FrozenSet[str], 'URDU...

FILE
    /home/manzur/.local/lib/python3.8/site-packages/urduhack/urdu_characters.py




In [13]:
import spacy

In [14]:
help (spacy)

Help on package spacy:

NAME
    spacy

PACKAGE CONTENTS
    __main__
    about
    attrs
    cli (package)
    compat
    displacy (package)
    errors
    git_info
    glossary
    kb
    lang (package)
    language
    lexeme
    lookups
    matcher (package)
    ml (package)
    morphology
    parts_of_speech
    pipe_analysis
    pipeline (package)
    schemas
    scorer
    strings
    symbols
    tests (package)
    tokenizer
    tokens (package)
    training (package)
    util
    vectors
    vocab

FUNCTIONS
    blank(name: str, *, vocab: Union[spacy.vocab.Vocab, bool] = True, config: Union[Dict[str, Any], thinc.config.Config] = {}, meta: Dict[str, Any] = {}) -> spacy.language.Language
        Create a blank nlp object for a given language code.
        
        name (str): The language code, e.g. "en".
        vocab (Vocab): A Vocab object. If True, a vocab is created.
        config (Dict[str, Any] / Config): Optional config overrides.
        meta (Dict[str, Any]): Override

In [15]:
dfw2v = urdu_source.copy()
dfw2v.head()

Data Label
0  نہ سنگ خشت درد سے بھر نہ روئیں ہم ہزار بار ہمی...   Sad
1  بازیچۂ اطفال دنیا مرے آگے ہوتا شب روز تماشا مر...   Sad
2  نہ ہماری قسمت وصال یار ہوتا جیتے رہتے یہی انتظ...   Sad
3  بات تم کیا تمہیں انداز گفتگو کیا نہ شعلہ میں ک...   Sad
4  ہزاروں خواہشیں ایسی خواہش دم نکلے بہت نکلے مرے...   Sad

In [16]:
from urduhack.models.lemmatizer import lemmatizer
def lemitizeStr(str):
    lemme_str = ""
    temp = lemmatizer.lemma_lookup(str)
    for t in temp:
        lemme_str += t[0] + " "
    
    return lemme_str
urdu_source['lemmatized_Data'] = urdu_source['Data'].apply(lemitizeStr)

In [17]:
urdu_source[['Data', 'lemmatized_Data']].head(10)
dfw2v = urdu_source.copy()

In [18]:
import spacy
def tokenizer(str):
    nlp = spacy.blank('ur')
    doc = nlp.tokenizer(str)
    return [i.text for i in doc]
dfw2v["Data_tokens"] = dfw2v["lemmatized_Data"].apply(tokenizer)


In [19]:
import gensim 

model_word2vec = gensim.models.word2vec.Word2Vec(sentences=dfw2v["Data_tokens"], vector_size=132,window=5, workers=10, min_count = 1)
#applying word2vec on tokens

/home/manzur/.local/lib/python3.8/site-packages/gensim/similarities/__init__.py:15: UserWarning: The gensim.similarities.levenshtein submodule is disabled, because the optional Levenshtein package <https://pypi.org/project/python-Levenshtein/> is unavailable. Install Levenhstein (e.g. `pip install python-Levenshtein`) to suppress this warning.
  warnings.warn(msg)


In [20]:
model_word2vec.wv["سنگ"] #vector space of a particular word

array([ 0.01334044, -0.00448805, -0.01082796,  0.00335869,  0.00296322,
       -0.01646943,  0.01412138,  0.00333421, -0.00264943, -0.00547214,
        0.00623154,  0.01450807,  0.03662779,  0.01855117,  0.00519424,
       -0.00257059, -0.02590322,  0.00142862, -0.0190815 , -0.00691745,
        0.01143408, -0.00269976,  0.00308355, -0.00775834,  0.02751441,
        0.02309883, -0.01478067,  0.03425602, -0.01409628,  0.02635781,
        0.02093509, -0.02674006, -0.01694933, -0.00577584,  0.02183926,
       -0.01411248,  0.00880227,  0.02661048, -0.01282692,  0.00984476,
       -0.00629753,  0.03271089, -0.00229695, -0.02862997,  0.00300814,
       -0.01381418, -0.01842994,  0.02418084, -0.01129773, -0.00840614,
        0.01075874,  0.0071564 ,  0.02426361, -0.01026133,  0.00222609,
       -0.00268809, -0.00945551,  0.01219366,  0.01760941,  0.02170892,
       -0.00982046, -0.0019392 , -0.01579538, -0.01449701,  0.01046728,
       -0.01283267, -0.01702332,  0.01778335, -0.0188407 , -0.00

In [21]:
    import tensorflow as tf 
    import keras
    from keras.preprocessing.text import Tokenizer
    token = Tokenizer()
    
    #converting tokens into sequence using keras so that can be used for training a word2vec model:
    
    token.fit_on_texts(dfw2v["Data_tokens"])
    encoded = token.texts_to_sequences(dfw2v["Data_tokens"]) 
    
   #training the word2vec model:
        
    train_vectors = tf.keras.preprocessing.sequence.pad_sequences(encoded,padding='post',dtype=int)
    train_label = dfw2v.Label
#splitting data of word2vec model in train and test: 
    (train_data,test_data, train_label, test_label) = train_test_split(train_vectors, train_label, test_size=0.2, shuffle = True)
    def DecisionTree_w2v_classifier(train_data, train_label, test_data, test_label):
    # Training
     clf = DecisionTreeClassifier(max_depth=100)
     clf_fit = clf.fit(train_data,train_label)
     # Testing
     test_prediction_w2v_D_T = clf_fit.predict(test_data)
     return classification_report(test_prediction_w2v_D_T, test_label), confusion_matrix(test_prediction_w2v_D_T,test_label)
class_report , conf_matrix = DecisionTree_w2v_classifier(train_data,train_label, test_data, test_label)
print('Results of DecisionTree CLASSIFIER on Word2Vec Vectorizer\n')
print(class_report)

   
    

Results of DecisionTree CLASSIFIER on Word2Vec Vectorizer

              precision    recall  f1-score   support

       Comic       0.43      0.18      0.25        17
   Patriotic       0.77      0.67      0.71        15
   Religious       0.47      0.56      0.51        16
         Sad       0.38      0.67      0.48        12

    accuracy                           0.50        60
   macro avg       0.51      0.52      0.49        60
weighted avg       0.52      0.50      0.48        60



In [22]:
print(transformers.__version__)

NameError: name 'transformers' is not defined

In [ ]:
print(conf_matrix)

In [ ]:
def SVM_w2v_classifier(train_data, train_label, test_data, test_label):
    # Training
     SVM = svm.LinearSVC(max_iter=100)
     SVM1 = SVM.fit(train_data,train_label)
     # Testing
     test_prediction_w2v_D_T = SVM1.predict(test_data)
     return classification_report(test_prediction_w2v_D_T, test_label), confusion_matrix(test_prediction_w2v_D_T,test_label)
print('Results of SVM CLASSIFIER on Word2Vec Vectorizer\n')
class_report , conf_matrix = SVM_w2v_classifier(train_data, train_label, test_data,test_label)
print(class_report)